name       : perl-test-perltidy
version    : '20220902'
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/Test-PerlTidy-20220902.tar.gz : 5e68ef619389941b28e7176f2d82ca76a3cf32fa7bb3633ca88d01744adc4838
homepage   : https://metacpan.org/pod/Test::PerlTidy
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::PerlTidy - check that all your files are tidy
description: |
    Test::PerlTidy - check that all your files are tidy
builddeps  :
    - perl-module-build
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
