name       : perl-test-perltidy
version    : '20230226'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/Test-PerlTidy-20230226.tar.gz : c0e242110795795d4dbb6c44166ce5574f5c7edba78a789d1bcae76685d803c1
homepage   : https://metacpan.org/pod/Test::PerlTidy
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::PerlTidy - check that all your files are tidy
description: |
    Test::PerlTidy - check that all your files are tidy
builddeps  :
    - perl-module-build
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
