name       : perl-test-perltidy
version    : 20130104
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/L/LA/LARRYL/Test-PerlTidy-20130104.tar.gz : 3f15d9f3f4811e348594620312258d75095237925b491ada623fa73ac9d2b9c8
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::PerlTidy - check that all your files are tidy
description: |
    Test::PerlTidy - check that all your files are tidy
#builddeps  :
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
